In [30]:
#random matrices setup
import numpy as np
a1 = np.random.randint(-1000,1000,size=(4,5))
a2 = np.random.randint(-1000,1000,size=(4,5))
print(a1)
print(a2)

[[-992 -521  523  201  404]
 [ 153 -791 -168  807  528]
 [ 993 -158  135 -267   75]
 [ 758 -306 -638 -491 -139]]
[[-651  824  440 -574  915]
 [-708  615  632  403 -493]
 [ 431 -394 -232  225 -852]
 [-528  898   99 -838  229]]


### Property 1: Det(AB) = Det(A)*Det(b)

In [3]:
d1 = np.linalg.det(a1)
d2 = np.linalg.det(a2)
d12tgt = np.linalg.det(a1@a2)
d12sep = d1*d2

In [ ]:
print('Determinant calculated together:' + '\t' + str(d12tgt))
print('Determinant calculated separately:' + '\t' + str(d12sep))

### Property 2: The sum of two determinants does not equal to the determinant of the sum of the two matrices

In [ ]:
d12sumsep = d1+d2
d12sumtgt = np.linalg.det(a1+a2)
print('Sum of determinant calculated together:' + '\t' + str(d12sumtgt))
print('Sum of determinant calculated separately:' + '\t' + str(d12sumsep))

In [31]:
a1t = np.transpose(a1)
da1a1t = np.linalg.det(a1@a1t)
da1ta1 = np.linalg.det(a1t@a1)

print('Determinant of AAt: ' + '\t' + str(da1a1t))
print('Determinant of AtA: ' + '\t' + str(da1ta1))



Determinant of AAt: 	7.456730181518743e+23
Determinant of AtA: 	-22545556399321.32
